# Generated by Django 6.0.3 on 2026-04-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmployeesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emp_id",
                    models.CharField(max_length=10, verbose_name="Employeee ID"),
                ),
                (
                    "emp_name",
                    models.CharField(max_length=30, verbose_name="Employee Name"),
                ),
                (
                    "emp_designation",
                    models.CharField(
                        max_length=50, verbose_name="Employeee Designation"
                    ),
                ),
            ],
        ),
    ]
