# Generated by Django 6.0.3 on 2026-04-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProgrammersModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prog_id",
                    models.CharField(max_length=10, verbose_name="Programmer ID"),
                ),
                (
                    "prog_name",
                    models.CharField(max_length=30, verbose_name="Programmer Name"),
                ),
                (
                    "prog_lang",
                    models.CharField(
                        max_length=30, verbose_name="Programmer's Language"
                    ),
                ),
            ],
        ),
    ]
