# Generated by Django 6.0.3 on 2026-04-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stu_rollno", models.CharField(max_length=10)),
                ("stu_name", models.CharField(max_length=50)),
                ("branch", models.CharField(max_length=30)),
            ],
        ),
    ]
