# Generated by Django 6.0.3 on 2026-04-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentsmodel",
            name="branch",
            field=models.CharField(max_length=30, verbose_name="Student's Branch"),
        ),
        migrations.AlterField(
            model_name="studentsmodel",
            name="stu_name",
            field=models.CharField(max_length=50, verbose_name="Student's Name"),
        ),
        migrations.AlterField(
            model_name="studentsmodel",
            name="stu_rollno",
            field=models.CharField(max_length=10, verbose_name="Student's Roll No."),
        ),
    ]
