# Generated by Django 6.0.3 on 2026-04-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TeachersModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("t_id", models.CharField(max_length=10, verbose_name="Teacher's ID")),
                (
                    "t_name",
                    models.CharField(max_length=30, verbose_name="Teacher's Name"),
                ),
                (
                    "t_subject",
                    models.CharField(max_length=30, verbose_name="Teacher's Subject"),
                ),
            ],
        ),
    ]
